### ISSUE TITLE
Could not create logging file: No such file or directory

### ISSUE THREAD

**Issue by nathan-sixnines** [amd/OpenCL-caffe#26]
After downloading and configuring the mnist example for caffe, it i'm having an issue training.

When I run

> ./examples/mnist/train_lenet.sh

It seems to fail to make a log file multiple times, but then after that it's off to the races and it runs the remainder of the training script to completion. This is the first part of the output:

Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165532.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165533.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165533.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165539.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165539.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165546.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165546.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165546.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165546.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165546.10424!Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165546.10424!Forwarding mnist,  time 2.000000 ms
Forwarding label_mnist_1_split, time 0.000000 ms
Forwarding conv1,   time 270.000000 ms
Forwarding pool1,   time 0.000000 ms
....

After the script runs I end up with lenet_iter_10000.caffemodel  and lenet_iter_10000.solverstate, but when I use the command:

> ./build/tools/caffe test examples/mnist/lenet_train_test.prototxt -weights examples/mnist/lenet_iter_10000.caffemodel -gpu 3 -iterations 100

I get this output:

caffe: command line brew
usage: caffe <command> <args>

commands:
  train           train or finetune a model
  test            score a model
  device_query    show GPU diagnostic information
  time            benchmark model execution time

  Flags from //home/nathan/OpenCL-caffe/tools/caffe.cpp:
    -gpu (Run in GPU mode on given device ID.) type: int32 default: -1
      currently: 3
    -iterations (The number of iterations to run.) type: int32 default: 50
      currently: 100
    -model (The model definition protocol buffer text file..) type: string
      default: ""
    -snapshot (Optional; the snapshot solver state to resume training.)
      type: string default: ""
    -solver (The solver definition protocol buffer text file.) type: string
      default: ""
    -weights (Optional; the pretrained weights to initialize finetuning. Cannot
      be set simultaneously with snapshot.) type: string default: ""
      currently: "examples/mnist/lenet_iter_10000.caffemodel"
Could not create logging file: No such file or directory
COULD NOT CREATE A LOGGINGFILE 20160113-165918.10446!

So it seems like unless I fix this logging issue I won't be able to tell if caffe is actually working or not, because I can't find or see the output of the results of the testing or training anywhere.

**Comment by mpekalski** [comment]
You have to create a **log**  folder in the place from which you run the code, probably that would be **OpenCL-caffe** folder.

**Comment by gujunli** [comment]
it is easy to fix. please mkdir log at the same level of src

**Comment by nathan-sixnines** [comment]
Awesome! Thank you guys.
