### ISSUE TITLE
Trouble with classify.py

### ISSUE THREAD

**Issue by nathan-sixnines** [amd/OpenCL-caffe#41]
I am trying to get the classification functionality of Caffe to work.

I am running this command, which I found [here](https://github.com/BVLC/caffe/issues/896) to test classification with the classify.py defaults:

> /python/classify.py --raw_scale=255 examples/images/cat.jpg  out.npy

It's saying it failed to parse the netParameter file, but I find that to be sort of confusing because it prints out the details of the network from that file before it fails.

Any help or tips would be appreciated, not sure how to proceed.

This is the printout:

nathan@10:~/OpenCL-caffe$ ./python/classify.py --raw_scale=255 examples/images/cat.jpg  out.npy
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0402 00:38:06.527276  8318 device.cpp:233] Number of platforms found:1
I0402 00:38:06.527321  8318 device.cpp:265]     CL_PLATFORM_NAME        AMD Accelerated Parallel Processing
I0402 00:38:06.527338  8318 device.cpp:265]     CL_PLATFORM_PROFILE     FULL_PROFILE
I0402 00:38:06.527351  8318 device.cpp:265]     CL_PLATFORM_VERSION     OpenCL 2.0 AMD-APP (1800.8)
I0402 00:38:06.527365  8318 device.cpp:265]     CL_PLATFORM_VENDOR      Advanced Micro Devices, Inc.
I0402 00:38:06.527379  8318 device.cpp:265]     CL_PLATFORM_EXTENSIONS  cl_khr_icd cl_amd_event_callback cl_amd_offline_devices
I0402 00:38:06.527395  8318 device.cpp:289] Number of devices found:4
I0402 00:38:06.527403  8318 device.cpp:291]     DeviceID:       0x3735180
I0402 00:38:06.527420  8318 device.cpp:380]      Device Type:   CL_DEVICE_TYPE_GPU
I0402 00:38:06.527434  8318 device.cpp:407]     Is it integrated GPU?:  0
I0402 00:38:06.527448  8318 device.cpp:407]     Max clock frequency MHz:       880
I0402 00:38:06.527462  8318 device.cpp:407]     Host-Device unified mem:       0
I0402 00:38:06.527477  8318 device.cpp:407]     ECC support:    0
I0402 00:38:06.527489  8318 device.cpp:407]     Endian little:  1
I0402 00:38:06.527503  8318 device.cpp:407]     Max compute units:      28
I0402 00:38:06.527529  8318 device.cpp:407]     Max work group size:    256
I0402 00:38:06.527541  8318 device.cpp:407]     Max work item dimensions:      3
I0402 00:38:06.527555  8318 device.cpp:407]     Max work item sizes:    0x100
I0402 00:38:06.527570  8318 device.cpp:403]      CL_DEVICE_QUEUE_PROPERTIES:   CL_QUEUE_PROFILING_ENABLE
I0402 00:38:06.527585  8318 device.cpp:391]      CL_DEVICE_EXECUTION_CAPABILITIES:      CL_EXEC_KERNEL
I0402 00:38:06.527598  8318 device.cpp:407]     Max mem alloc size:     2128871424
I0402 00:38:06.527612  8318 device.cpp:407]     Global mem size:        2960130048
I0402 00:38:06.527626  8318 device.cpp:407]     Local mem size: 32768
I0402 00:38:06.527638  8318 device.cpp:291]     DeviceID:       0x3ca1fe0
I0402 00:38:06.527652  8318 device.cpp:380]      Device Type:   CL_DEVICE_TYPE_GPU
I0402 00:38:06.527667  8318 device.cpp:407]     Is it integrated GPU?:  0
I0402 00:38:06.527680  8318 device.cpp:407]     Max clock frequency MHz:       880
I0402 00:38:06.527693  8318 device.cpp:407]     Host-Device unified mem:       0
I0402 00:38:06.527706  8318 device.cpp:407]     ECC support:    0
I0402 00:38:06.527720  8318 device.cpp:407]     Endian little:  1
I0402 00:38:06.527734  8318 device.cpp:407]     Max compute units:      28
I0402 00:38:06.527747  8318 device.cpp:407]     Max work group size:    256
I0402 00:38:06.527760  8318 device.cpp:407]     Max work item dimensions:      3
I0402 00:38:06.527775  8318 device.cpp:407]     Max work item sizes:    0x100
I0402 00:38:06.527788  8318 device.cpp:403]      CL_DEVICE_QUEUE_PROPERTIES:   CL_QUEUE_PROFILING_ENABLE
I0402 00:38:06.527802  8318 device.cpp:391]      CL_DEVICE_EXECUTION_CAPABILITIES:      CL_EXEC_KERNEL
I0402 00:38:06.527815  8318 device.cpp:407]     Max mem alloc size:     2205941760
I0402 00:38:06.527829  8318 device.cpp:407]     Global mem size:        3183476736
I0402 00:38:06.527842  8318 device.cpp:407]     Local mem size: 32768
I0402 00:38:06.527855  8318 device.cpp:291]     DeviceID:       0x3c74630
I0402 00:38:06.527869  8318 device.cpp:380]      Device Type:   CL_DEVICE_TYPE_GPU
I0402 00:38:06.527883  8318 device.cpp:407]     Is it integrated GPU?:  0
I0402 00:38:06.527896  8318 device.cpp:407]     Max clock frequency MHz:       880
I0402 00:38:06.527909  8318 device.cpp:407]     Host-Device unified mem:       0
I0402 00:38:06.527923  8318 device.cpp:407]     ECC support:    0
I0402 00:38:06.527936  8318 device.cpp:407]     Endian little:  1
I0402 00:38:06.527951  8318 device.cpp:407]     Max compute units:      28
I0402 00:38:06.527963  8318 device.cpp:407]     Max work group size:    256
I0402 00:38:06.527982  8318 device.cpp:407]     Max work item dimensions:      3
I0402 00:38:06.527995  8318 device.cpp:407]     Max work item sizes:    0x100
I0402 00:38:06.528009  8318 device.cpp:403]      CL_DEVICE_QUEUE_PROPERTIES:   CL_QUEUE_PROFILING_ENABLE
I0402 00:38:06.528023  8318 device.cpp:391]      CL_DEVICE_EXECUTION_CAPABILITIES:      CL_EXEC_KERNEL
I0402 00:38:06.528038  8318 device.cpp:407]     Max mem alloc size:     2205941760
I0402 00:38:06.528050  8318 device.cpp:407]     Global mem size:        3183476736
I0402 00:38:06.528064  8318 device.cpp:407]     Local mem size: 32768
I0402 00:38:06.528077  8318 device.cpp:291]     DeviceID:       0x3e60b10
I0402 00:38:06.528091  8318 device.cpp:380]      Device Type:   CL_DEVICE_TYPE_GPU
I0402 00:38:06.528105  8318 device.cpp:407]     Is it integrated GPU?:  0
I0402 00:38:06.528118  8318 device.cpp:407]     Max clock frequency MHz:       880
I0402 00:38:06.528131  8318 device.cpp:407]     Host-Device unified mem:       0
I0402 00:38:06.528144  8318 device.cpp:407]     ECC support:    0
I0402 00:38:06.528158  8318 device.cpp:407]     Endian little:  1
I0402 00:38:06.528172  8318 device.cpp:407]     Max compute units:      28
I0402 00:38:06.528184  8318 device.cpp:407]     Max work group size:    256
I0402 00:38:06.528203  8318 device.cpp:407]     Max work item dimensions:      3
I0402 00:38:06.528216  8318 device.cpp:407]     Max work item sizes:    0x100
I0402 00:38:06.528230  8318 device.cpp:403]      CL_DEVICE_QUEUE_PROPERTIES:   CL_QUEUE_PROFILING_ENABLE
I0402 00:38:06.528255  8318 device.cpp:391]      CL_DEVICE_EXECUTION_CAPABILITIES:      CL_EXEC_KERNEL
I0402 00:38:06.528270  8318 device.cpp:407]     Max mem alloc size:     2205941760
I0402 00:38:06.528283  8318 device.cpp:407]     Global mem size:        3183476736
I0402 00:38:06.528296  8318 device.cpp:407]     Local mem size: 32768
I0402 00:38:06.528312  8318 device.cpp:90] Picked default device type : dGPU 0
I0402 00:38:12.589821  8318 device.cpp:159] Build Program
CPU mode
I0402 00:38:12.591653  8318 net.cpp:43] Initializing net from parameters:
name: "CaffeNet"
input: "data"
input_dim: 10
input_dim: 3
input_dim: 227
input_dim: 227
state {
  phase: TEST
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  convolution_param {
    num_output: 96
    kernel_size: 11
    stride: 4
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "norm1"
  type: "LRN"
  bottom: "pool1"
  top: "norm1"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "norm1"
  top: "conv2"
  convolution_param {
    num_output: 256
    pad: 2
    kernel_size: 5
    group: 2
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "norm2"
  type: "LRN"
  bottom: "pool2"
  top: "norm2"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "conv3"
  type: "Convolution"
  bottom: "norm2"
  top: "conv3"
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
  }
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "conv3"
  top: "conv3"
}
layer {
  name: "conv4"
  type: "Convolution"
  bottom: "conv3"
  top: "conv4"
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    group: 2
  }
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "conv5"
  type: "Convolution"
  bottom: "conv4"
  top: "conv5"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    group: 2
  }
}
layer {
  name: "relu5"
  type: "ReLU"
  bottom: "conv5"
  top: "conv5"
}
layer {
  name: "pool5"
  type: "Pooling"
  bottom: "conv5"
  top: "pool5"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "fc6"
  type: "InnerProduct"
  bottom: "pool5"
  top: "fc6"
  inner_product_param {
    num_output: 4096
  }
}
layer {
  name: "relu6"
  type: "ReLU"
  bottom: "fc6"
  top: "fc6"
}
layer {
  name: "drop6"
  type: "Dropout"
  bottom: "fc6"
  top: "fc6"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "fc7"
  type: "InnerProduct"
  bottom: "fc6"
  top: "fc7"
  inner_product_param {
    num_output: 4096
  }
}
layer {
  name: "relu7"
  type: "ReLU"
  bottom: "fc7"
  top: "fc7"
}
layer {
  name: "drop7"
  type: "Dropout"
  bottom: "fc7"
  top: "fc7"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "fc8"
  type: "InnerProduct"
  bottom: "fc7"
  top: "fc8"
  inner_product_param {
    num_output: 1000
  }
}
layer {
  name: "prob"
  type: "Softmax"
  bottom: "fc8"
  top: "prob"
}
I0402 00:38:12.592326  8318 net.cpp:380] Input 0 -> data
I0402 00:38:12.592362  8318 layer_factory.hpp:74] Creating layer conv1
I0402 00:38:12.592377  8318 net.cpp:90] Creating Layer conv1
I0402 00:38:12.592386  8318 net.cpp:423] conv1 <- data
I0402 00:38:12.592397  8318 net.cpp:378] conv1 -> conv1
I0402 00:38:12.592417  8318 net.cpp:120] Setting up conv1
I0402 00:38:12.593049  8318 net.cpp:127] Top shape: 10 96 55 55 (2904000)
I0402 00:38:12.593086  8318 layer_factory.hpp:74] Creating layer relu1
I0402 00:38:12.593103  8318 net.cpp:90] Creating Layer relu1
I0402 00:38:12.593113  8318 net.cpp:423] relu1 <- conv1
I0402 00:38:12.593123  8318 net.cpp:367] relu1 -> conv1 (in-place)
I0402 00:38:12.593135  8318 net.cpp:120] Setting up relu1
I0402 00:38:12.593152  8318 net.cpp:127] Top shape: 10 96 55 55 (2904000)
I0402 00:38:12.593163  8318 layer_factory.hpp:74] Creating layer pool1
I0402 00:38:12.593174  8318 net.cpp:90] Creating Layer pool1
I0402 00:38:12.593183  8318 net.cpp:423] pool1 <- conv1
I0402 00:38:12.593192  8318 net.cpp:378] pool1 -> pool1
I0402 00:38:12.593204  8318 net.cpp:120] Setting up pool1
I0402 00:38:12.593228  8318 net.cpp:127] Top shape: 10 96 27 27 (699840)
I0402 00:38:12.593238  8318 layer_factory.hpp:74] Creating layer norm1
I0402 00:38:12.593250  8318 net.cpp:90] Creating Layer norm1
I0402 00:38:12.593260  8318 net.cpp:423] norm1 <- pool1
I0402 00:38:12.593269  8318 net.cpp:378] norm1 -> norm1
I0402 00:38:12.593281  8318 net.cpp:120] Setting up norm1
I0402 00:38:12.593294  8318 net.cpp:127] Top shape: 10 96 27 27 (699840)
I0402 00:38:12.593302  8318 layer_factory.hpp:74] Creating layer conv2
I0402 00:38:12.593314  8318 net.cpp:90] Creating Layer conv2
I0402 00:38:12.593327  8318 net.cpp:423] conv2 <- norm1
I0402 00:38:12.593336  8318 net.cpp:378] conv2 -> conv2
I0402 00:38:12.593348  8318 net.cpp:120] Setting up conv2
I0402 00:38:12.593807  8318 net.cpp:127] Top shape: 10 256 27 27 (1866240)
I0402 00:38:12.593847  8318 layer_factory.hpp:74] Creating layer relu2
I0402 00:38:12.593861  8318 net.cpp:90] Creating Layer relu2
I0402 00:38:12.593870  8318 net.cpp:423] relu2 <- conv2
I0402 00:38:12.593883  8318 net.cpp:367] relu2 -> conv2 (in-place)
I0402 00:38:12.593896  8318 net.cpp:120] Setting up relu2
I0402 00:38:12.593909  8318 net.cpp:127] Top shape: 10 256 27 27 (1866240)
I0402 00:38:12.593919  8318 layer_factory.hpp:74] Creating layer pool2
I0402 00:38:12.593930  8318 net.cpp:90] Creating Layer pool2
I0402 00:38:12.593940  8318 net.cpp:423] pool2 <- conv2
I0402 00:38:12.593950  8318 net.cpp:378] pool2 -> pool2
I0402 00:38:12.593964  8318 net.cpp:120] Setting up pool2
I0402 00:38:12.593982  8318 net.cpp:127] Top shape: 10 256 13 13 (432640)
I0402 00:38:12.593992  8318 layer_factory.hpp:74] Creating layer norm2
I0402 00:38:12.594004  8318 net.cpp:90] Creating Layer norm2
I0402 00:38:12.594014  8318 net.cpp:423] norm2 <- pool2
I0402 00:38:12.594024  8318 net.cpp:378] norm2 -> norm2
I0402 00:38:12.594036  8318 net.cpp:120] Setting up norm2
I0402 00:38:12.594051  8318 net.cpp:127] Top shape: 10 256 13 13 (432640)
I0402 00:38:12.594060  8318 layer_factory.hpp:74] Creating layer conv3
I0402 00:38:12.594074  8318 net.cpp:90] Creating Layer conv3
I0402 00:38:12.594084  8318 net.cpp:423] conv3 <- norm2
I0402 00:38:12.594094  8318 net.cpp:378] conv3 -> conv3
I0402 00:38:12.594106  8318 net.cpp:120] Setting up conv3
I0402 00:38:12.595118  8318 net.cpp:127] Top shape: 10 384 13 13 (648960)
I0402 00:38:12.595156  8318 layer_factory.hpp:74] Creating layer relu3
I0402 00:38:12.595171  8318 net.cpp:90] Creating Layer relu3
I0402 00:38:12.595180  8318 net.cpp:423] relu3 <- conv3
I0402 00:38:12.595194  8318 net.cpp:367] relu3 -> conv3 (in-place)
I0402 00:38:12.595207  8318 net.cpp:120] Setting up relu3
I0402 00:38:12.595219  8318 net.cpp:127] Top shape: 10 384 13 13 (648960)
I0402 00:38:12.595229  8318 layer_factory.hpp:74] Creating layer conv4
I0402 00:38:12.595242  8318 net.cpp:90] Creating Layer conv4
I0402 00:38:12.595250  8318 net.cpp:423] conv4 <- conv3
I0402 00:38:12.595262  8318 net.cpp:378] conv4 -> conv4
I0402 00:38:12.595275  8318 net.cpp:120] Setting up conv4
I0402 00:38:12.596067  8318 net.cpp:127] Top shape: 10 384 13 13 (648960)
I0402 00:38:12.596101  8318 layer_factory.hpp:74] Creating layer relu4
I0402 00:38:12.596115  8318 net.cpp:90] Creating Layer relu4
I0402 00:38:12.596124  8318 net.cpp:423] relu4 <- conv4
I0402 00:38:12.596137  8318 net.cpp:367] relu4 -> conv4 (in-place)
I0402 00:38:12.596150  8318 net.cpp:120] Setting up relu4
I0402 00:38:12.596163  8318 net.cpp:127] Top shape: 10 384 13 13 (648960)
I0402 00:38:12.596173  8318 layer_factory.hpp:74] Creating layer conv5
I0402 00:38:12.596184  8318 net.cpp:90] Creating Layer conv5
I0402 00:38:12.596194  8318 net.cpp:423] conv5 <- conv4
I0402 00:38:12.596204  8318 net.cpp:378] conv5 -> conv5
I0402 00:38:12.596216  8318 net.cpp:120] Setting up conv5
I0402 00:38:12.596774  8318 net.cpp:127] Top shape: 10 256 13 13 (432640)
I0402 00:38:12.596810  8318 layer_factory.hpp:74] Creating layer relu5
I0402 00:38:12.596824  8318 net.cpp:90] Creating Layer relu5
I0402 00:38:12.596834  8318 net.cpp:423] relu5 <- conv5
I0402 00:38:12.596845  8318 net.cpp:367] relu5 -> conv5 (in-place)
I0402 00:38:12.596859  8318 net.cpp:120] Setting up relu5
I0402 00:38:12.596871  8318 net.cpp:127] Top shape: 10 256 13 13 (432640)
I0402 00:38:12.596881  8318 layer_factory.hpp:74] Creating layer pool5
I0402 00:38:12.596892  8318 net.cpp:90] Creating Layer pool5
I0402 00:38:12.596902  8318 net.cpp:423] pool5 <- conv5
I0402 00:38:12.596912  8318 net.cpp:378] pool5 -> pool5
I0402 00:38:12.596925  8318 net.cpp:120] Setting up pool5
I0402 00:38:12.596945  8318 net.cpp:127] Top shape: 10 256 6 6 (92160)
I0402 00:38:12.596954  8318 layer_factory.hpp:74] Creating layer fc6
I0402 00:38:12.596966  8318 net.cpp:90] Creating Layer fc6
I0402 00:38:12.596976  8318 net.cpp:423] fc6 <- pool5
I0402 00:38:12.596985  8318 net.cpp:378] fc6 -> fc6
I0402 00:38:12.596998  8318 net.cpp:120] Setting up fc6
I0402 00:38:12.643108  8318 net.cpp:127] Top shape: 10 4096 (40960)
I0402 00:38:12.643144  8318 layer_factory.hpp:74] Creating layer relu6
I0402 00:38:12.643163  8318 net.cpp:90] Creating Layer relu6
I0402 00:38:12.643172  8318 net.cpp:423] relu6 <- fc6
I0402 00:38:12.643184  8318 net.cpp:367] relu6 -> fc6 (in-place)
I0402 00:38:12.643196  8318 net.cpp:120] Setting up relu6
I0402 00:38:12.643208  8318 net.cpp:127] Top shape: 10 4096 (40960)
I0402 00:38:12.643215  8318 layer_factory.hpp:74] Creating layer drop6
I0402 00:38:12.643235  8318 net.cpp:90] Creating Layer drop6
I0402 00:38:12.643244  8318 net.cpp:423] drop6 <- fc6
I0402 00:38:12.643254  8318 net.cpp:367] drop6 -> fc6 (in-place)
I0402 00:38:12.643265  8318 net.cpp:120] Setting up drop6
I0402 00:38:12.643287  8318 net.cpp:127] Top shape: 10 4096 (40960)
I0402 00:38:12.643296  8318 layer_factory.hpp:74] Creating layer fc7
I0402 00:38:12.643307  8318 net.cpp:90] Creating Layer fc7
I0402 00:38:12.643317  8318 net.cpp:423] fc7 <- fc6
I0402 00:38:12.643327  8318 net.cpp:378] fc7 -> fc7
I0402 00:38:12.643339  8318 net.cpp:120] Setting up fc7
I0402 00:38:12.664165  8318 net.cpp:127] Top shape: 10 4096 (40960)
I0402 00:38:12.664199  8318 layer_factory.hpp:74] Creating layer relu7
I0402 00:38:12.664214  8318 net.cpp:90] Creating Layer relu7
I0402 00:38:12.664224  8318 net.cpp:423] relu7 <- fc7
I0402 00:38:12.664237  8318 net.cpp:367] relu7 -> fc7 (in-place)
I0402 00:38:12.664257  8318 net.cpp:120] Setting up relu7
I0402 00:38:12.664266  8318 net.cpp:127] Top shape: 10 4096 (40960)
I0402 00:38:12.664275  8318 layer_factory.hpp:74] Creating layer drop7
I0402 00:38:12.664286  8318 net.cpp:90] Creating Layer drop7
I0402 00:38:12.664294  8318 net.cpp:423] drop7 <- fc7
I0402 00:38:12.664304  8318 net.cpp:367] drop7 -> fc7 (in-place)
I0402 00:38:12.664315  8318 net.cpp:120] Setting up drop7
I0402 00:38:12.664329  8318 net.cpp:127] Top shape: 10 4096 (40960)
I0402 00:38:12.664336  8318 layer_factory.hpp:74] Creating layer fc8
I0402 00:38:12.664348  8318 net.cpp:90] Creating Layer fc8
I0402 00:38:12.664360  8318 net.cpp:423] fc8 <- fc7
I0402 00:38:12.664369  8318 net.cpp:378] fc8 -> fc8
I0402 00:38:12.664381  8318 net.cpp:120] Setting up fc8
I0402 00:38:12.669795  8318 net.cpp:127] Top shape: 10 1000 (10000)
I0402 00:38:12.669828  8318 layer_factory.hpp:74] Creating layer prob
I0402 00:38:12.669843  8318 net.cpp:90] Creating Layer prob
I0402 00:38:12.669853  8318 net.cpp:423] prob <- fc8
I0402 00:38:12.669865  8318 net.cpp:378] prob -> prob
I0402 00:38:12.669879  8318 net.cpp:120] Setting up prob
I0402 00:38:12.669960  8318 net.cpp:127] Top shape: 10 1000 (10000)
I0402 00:38:12.669973  8318 net.cpp:197] prob does not need backward computation.
I0402 00:38:12.669983  8318 net.cpp:197] fc8 does not need backward computation.
I0402 00:38:12.669992  8318 net.cpp:197] drop7 does not need backward computation.
I0402 00:38:12.670001  8318 net.cpp:197] relu7 does not need backward computation.
I0402 00:38:12.670008  8318 net.cpp:197] fc7 does not need backward computation.
I0402 00:38:12.670017  8318 net.cpp:197] drop6 does not need backward computation.
I0402 00:38:12.670025  8318 net.cpp:197] relu6 does not need backward computation.
I0402 00:38:12.670033  8318 net.cpp:197] fc6 does not need backward computation.
I0402 00:38:12.670042  8318 net.cpp:197] pool5 does not need backward computation.
I0402 00:38:12.670050  8318 net.cpp:197] relu5 does not need backward computation.
I0402 00:38:12.670058  8318 net.cpp:197] conv5 does not need backward computation.
I0402 00:38:12.670066  8318 net.cpp:197] relu4 does not need backward computation.
I0402 00:38:12.670075  8318 net.cpp:197] conv4 does not need backward computation.
I0402 00:38:12.670083  8318 net.cpp:197] relu3 does not need backward computation.
I0402 00:38:12.670091  8318 net.cpp:197] conv3 does not need backward computation.
I0402 00:38:12.670100  8318 net.cpp:197] norm2 does not need backward computation.
I0402 00:38:12.670109  8318 net.cpp:197] pool2 does not need backward computation.
I0402 00:38:12.670117  8318 net.cpp:197] relu2 does not need backward computation.
I0402 00:38:12.670125  8318 net.cpp:197] conv2 does not need backward computation.
I0402 00:38:12.670135  8318 net.cpp:197] norm1 does not need backward computation.
I0402 00:38:12.670142  8318 net.cpp:197] pool1 does not need backward computation.
I0402 00:38:12.670151  8318 net.cpp:197] relu1 does not need backward computation.
I0402 00:38:12.670159  8318 net.cpp:197] conv1 does not need backward computation.
I0402 00:38:12.670167  8318 net.cpp:238] This network produces output prob
I0402 00:38:12.670188  8318 net.cpp:495] Collecting Learning Rate and Weight Decay.
I0402 00:38:12.670202  8318 net.cpp:250] Network initialization done.
I0402 00:38:12.670212  8318 net.cpp:251] Memory required for data: 62497920
F0402 00:38:12.982095  8318 upgrade_proto.cpp:956] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: ./python/../models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
**\* Check failure stack trace: ***
Aborted (core dumped)
nathan@10:~/OpenCL-caffe$

**Comment by naibaf7** [comment]
@Aeium 
It looks like it does not find the trained model. Where do you have that stored?
Either `models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel`
does not exist or is probably damaged.

**Comment by nathan-sixnines** [comment]
Oh, I see.

I had this problem because the script must have still been downloading the model.

I had ran this command in another terminal:

./scripts/download_model_binary.py models/bvlc_reference_caffenet

It works now so I guess that download must have still been going when I ran into that problem.
