### ISSUE TITLE
syncedmem.cpp:62 Check failed: error == 0 (-44 vs. 0)  -44 when running deepDream example

### ISSUE THREAD

**Issue by Spencer-Dawson** [amd/OpenCL-caffe#44]
Looks like clCreateKernel is returning CL_INVALID_PROGRAM. Any troubleshooting tips?

**Comment by davideverona** [comment]
Same problem for me running "make runtest" on OSX.

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl
