### ISSUE TITLE
Does OpenCL-caffe support Intel's Graphics cards?

### ISSUE THREAD

**Issue by thuhuwei** [amd/OpenCL-caffe#45]
Thanks

**Comment by rns4731** [comment]
👍

**Comment by alanoluo** [comment]
this is a great question!

**Comment by neoblizz** [comment]
I'm curious as well, I'd like to try this on Intel's Gen 9 on-chip gpu, can someone please confirm if this has been tried on Intel's gpu? If not, how much modifications would it take for it to work?

**Comment by naibaf7** [comment]
@neoblizz 
The official OpenCL Caffe branch contains an optional "INTEL_SPATIAL" kernel especially optimized for Intel GPUs.
URL: https://github.com/BVLC/caffe/tree/opencl
This branch here is by AMD and mostly optimized for AMD GPUs.

**Comment by neoblizz** [comment]
@naibaf7 Thank you!

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl

**Comment by saliltambe** [comment]
Hi,
 
This is indeed a great question. I tried running the official OpenCL branch of caffe located at:
https://github.com/BVLC/caffe/tree/opencl on my Mac with the following hardware details:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro12,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.7 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Graphics: Intel Iris Graphics 6100 1536 MB

I could run the Classification tutorial without any trouble. However, when I switch to the GPU mode, and try to run net.forward(), the kernel dies each time. Does this mean that this branch of OpenCL does not support integrated Graphics card? 

Thanks,

Sal
