### ISSUE TITLE
libclBLAS.so.2 cannot open

### ISSUE THREAD

**Issue by Jingsnow** [amd/OpenCL-caffe#46]
please answer me. When I run the mnist examples, I start this command:
sh examples/mnist/create_mnist.sh, while it failed. The error is: libclBLAS.so.2: cannot open shated object file: No such file or directory.  What I should do?
Thanks.

**Comment by gujunli** [comment]
Did you build clblas successfully? Set up the path?
Junli

**Comment by alanoluo** [comment]
cp　libclBLAS.so.2   /bin/lib

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl
