### ISSUE TITLE
Wiki page typo

### ISSUE THREAD

**Issue by rns4731** [amd/OpenCL-caffe#47]
cmake -DCMAKE_INSTALL_PATHATH=/opt/clBLAS2.7 -DOCL_VERSION TRING=2.0 -DCMAKE_BUILD_TYPE=Release -DPRECOMPILE_GEMM_PRECISION_SGEMM:BOOL=ON-DPRECOMPILE_GEMM_TRANS_NN:BOOL=ON -DPRECOMPILE_GEMM_TRANS_NT:BOOL=ON-DPRECOMPILE_GEMM_TRANS_TN:BOOL=ON -DPRECOMPILE_GEMM_TRANS_TT:BOOL=ON ..

should be 

cmake -DCMAKE_INSTALL_PATHATH=/opt/clBLAS2.7 -DOCL_VERSIONSTRING=2.0 -DCMAKE_BUILD_TYPE=Release -DPRECOMPILE_GEMM_PRECISION_SGEMM:BOOL=ON-DPRECOMPILE_GEMM_TRANS_NN:BOOL=ON -DPRECOMPILE_GEMM_TRANS_NT:BOOL=ON-DPRECOMPILE_GEMM_TRANS_TN:BOOL=ON -DPRECOMPILE_GEMM_TRANS_TT:BOOL=ON ..

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl

**Comment by janchk** [comment]
gstoner. This is bad that you solving problem like this.

**Comment by gstoner** [comment]
@ janchk We are working on a more optimized version of Caffe, but OpenCl is not the path we are  going forward with the port to our hardware.   We evaluated three languages paths
