### ISSUE TITLE
How to choose the AMD graphics card like the NVIDIA GPU which use "--gpus=xxx"?

### ISSUE THREAD

**Issue by wuzhijiexia** [amd/OpenCL-caffe#48]
Now, I want to do OpenCL-caffe using the AMD graphics card, but I don't know how to add the options. To caffe by the BVLC, you can use "--gpus=xxx" to specify the numberID of GPU. But here, how should I how to do?

**Comment by gujunli** [comment]
did you try -gpu=xx, does it work?

I remember by default, we select the first GPU that the system can find. do you wan to do it differently?
thanks
Junli

**Comment by wuzhijiexia** [comment]
You can check the numberID of the GPU using nvidia-smi. To the AMD graphics card, how should how to do? I try "-gpu=0" and "-gpu=1", but don't know whether the number is right.

**Comment by wuzhijiexia** [comment]
![image 1](https://cloud.githubusercontent.com/assets/19603119/15598799/4711f1da-2410-11e6-91c0-9e02147b84df.png)
The number by default is -1. Whether does this show we don't use the graphics card?

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl
