### ISSUE TITLE
How can I run caffe on intel MIC?

### ISSUE THREAD

**Issue by alanoluo** [amd/OpenCL-caffe#49]
在clBuildProgram()的-options 参数，您使用了+x clc++,但是这个好像只能在AMD的GPU中使用，我想用intel的MIC加速，请问怎么修改？

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl
