### ISSUE TITLE
VecLib issue on El Capitan

### ISSUE THREAD

**Issue by Tmbao** [amd/OpenCL-caffe#51]
Hi everyone, 

When trying to build caffe on OSX, I encountered this error:

```
[ 69%] Linking CXX shared library ../../lib/libcaffe.dylib
ld: framework not found vecLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcaffe.dylib] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2
```

Has anyone encountered this error, I tried to search for it on Google but I can't manage to resolve it.

Thanks.

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl
