### ISSUE TITLE
[HS] improving your hardware :

### ISSUE THREAD

**Issue by LifeIsStrange** [amd/OpenCL-caffe#53]
Sorry for the HS, but you should consider to use internally this language for designing gpus and cpus. 
It should give an advantage over nvidia. 
https://github.com/ucb-bar/chisel/

**Comment by gstoner** [comment]
Thank you we look this over

**Comment by LifeIsStrange** [comment]
Thank you for your consideration, less important you could consider this https://github.com/tracespace/pcb-stackup
In a general way you should consider opensource software for designing hardware, they are growing and could help you a lot. 
Sorry for my bad english.
