### ISSUE TITLE
I fail to run caffe, the question is about caffe::SyncedMemory::to_gpu(), but I don't know the reason

### ISSUE THREAD

**Issue by wuzhijiexia** [amd/OpenCL-caffe#54]
When I run caffe, the error show like this.
![image 2](https://cloud.githubusercontent.com/assets/19603119/16979976/810303ba-4e96-11e6-9736-fcf7ff29dd16.png)
I annotate these of caffe::SyncedMemory::to_gpu() on the file src/caffe/syncedmem.cpp. 
![image 3](https://cloud.githubusercontent.com/assets/19603119/16980247/ad4e6314-4e97-11e6-8a92-a91a02e3481d.png)
Then, recompile and setup. I can run caffe normally. But I think the method will influence caffe badly.
I want to know another new method which makes caffe work normally but don't need to annotate these sentences.

**Comment by gstoner** [comment]
This was experimental branch of Caffe for OpenCL, we know recommend you use the now official OpenCL port of Caffe in BVLC GitHub Repo at https://github.com/BVLC/caffe/tree/opencl
