### ISSUE TITLE
Your email is not correct

### ISSUE THREAD

**Issue by roysG** [amd/OpenCL-caffe#62]
Hi Junil, i tried to send you email, but it was invalid.

The email is: Junli.Gu@amd.com

Please let me know your email, i have question, thanks.

**Comment by naibaf7** [comment]
@roysG Note that Junli is not working on this project anymore. This project is abandoned by AMD.

If you want to use Caffe on AMD GPUs, you have two other options available:
- Official OpenCL branch of BVLC: https://github.com/BVLC/caffe/tree/opencl
- HIP Caffe by AMD: https://github.com/ROCmSoftwarePlatform/hipCaffe

see what works best for you and ask questions there.
